set -g status off
# set-option -g status-position top
set -g mouse on

set -g allow-passthrough on
unbind C-b
set -g prefix M-Space
bind M-Space send-prefix


set -g base-index 1
set-option -sa terminal-overrides ",xterm:Tc"
set -g pane-base-index 1


# Vim-style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Use wl-copy and wl-paste for clipboard integration (Wayland compatibility)
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'wl-copy'

# Clear the screen in the active pane
# bind C-l send-keys -t ! 'clear' C-m

# Plugin configurations
set -g @plugin 'christoomey/vim-tmux-navigator'
set-option -g update-environment "DISPLAY"

## Catppuccin Theme 
# set -g @plugin 'dreamsofcode-io/catppuccin-tmux'

# Additional Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# Set vi-mode for copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

#Load latest Path variables
set-option -g default-command "exec $SHELL"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
